### ISSUE TITLE
backslashes in strings should be backslashed

### ISSUE THREAD

**Issue by winterwolf** [26F-Studio/Emmy-love-api#8]
`love.keyboard.lua` - lines `66` and `205`:

Wrong:
```lua
---| "'\'" #Backslash key
```
Correct:
```lua
---| "'\\'" #Backslash key
```

**Comment by ImpleLee** [comment]
Maybe we should fix all strings that come with symbols...

**Comment by ImpleLee** [comment]
Types are now all quoted, which should be fixed.
